local opt = vim.opt

opt.number         = true
opt.relativenumber = true
opt.tabstop        = 2
opt.shiftwidth     = 2
opt.expandtab      = true
opt.smartindent    = true
opt.ignorecase     = true
opt.smartcase      = true
opt.hlsearch       = false
opt.incsearch      = true
opt.termguicolors  = true
opt.scrolloff      = 8
opt.sidescrolloff  = 8
opt.signcolumn     = "yes"
opt.cursorline     = true
opt.wrap           = false
opt.colorcolumn    = "80"
opt.swapfile       = false
opt.backup         = false
opt.undofile       = true
opt.undodir        = vim.fn.stdpath "data" .. "/undodir"
opt.updatetime     = 250
opt.timeoutlen     = 400
opt.splitbelow     = true
opt.splitright     = true
opt.clipboard      = "unnamedplus"
